[Interface]
PrivateKey = iHe3R3Hdv376dH1+KpNx6kb5U6xCBWqRIB9mQIGgF1g=
Address = 10.0.0.2/32
DNS = 1.1.1.1

[Peer]
PublicKey = /HVbd3Jdpx5ARzHhS8zTFqZXZP/HocbpMgTTF+qn63w=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 72.155.88.236:51820
PersistentKeepalive = 25
