[Interface]
PrivateKey = iHe3R3Hdv376dH1+KpNx6kb5U6xCBWqRIB9mQIGgF1g=
Address = 10.0.0.2/32
DNS = 1.1.1.1

[Peer]
# TODO: điền public key server (bắt buộc)
PublicKey = REPLACE_SERVER_PUBLIC_KEY
# TODO: nếu có PresharedKey thì điền, nếu không thì xóa dòng này
# PresharedKey = REPLACE_PSK
AllowedIPs = 0.0.0.0/0, ::/0
# TODO: điền endpoint server (host:port), ví dụ vpn.example.com:51820
Endpoint = REPLACE_ENDPOINT
PersistentKeepalive = 25
